CREATE DATABASE `JKUERY` /*!40100 DEFAULT CHARACTER SET utf8 */;
DROP TABLE IF EXISTS `JKUERY`.`JSON`;
CREATE TABLE  `JKUERY`.`JSON` (
  `ID` tinyint(4) NOT NULL AUTO_INCREMENT,
  `ORG` tinyint(4) unsigned NOT NULL DEFAULT '1',
  `HD_TICKET_RULE_ID` tinyint(3) unsigned DEFAULT NULL,
  `JDATA` mediumtext,
  `SQLstr` text,
  `PURPOSE` varchar(200) NOT NULL DEFAULT '',
  `CREATED` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `MODIFIED` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `ORG_IDX` (`ORG`)
) ENGINE=MyISAM AUTO_INCREMENT=100 DEFAULT CHARSET=utf8;

DROP TRIGGER IF EXISTS JKUERY.ceationtimeJSON;
DELIMITER //
CREATE TRIGGER JKUERY.ceationtimeJSON
BEFORE INSERT ON JSON
FOR EACH ROW
BEGIN
	IF NEW.CREATED = '0000-00-00 00:00:00' THEN
		SET NEW.CREATED = NOW();
	END IF;
	IF NEW.JDATA IS NULL THEN
		SET NEW.JDATA = '{}';
	END IF;
END;
//